version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  python_project:
    image: python_project:latest 
    expose:
      - "8080"
  golang_project:
    image: go_app:latest
    expose:
      - "8080"
