version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  python_project:
    image: flyingsmurf/todo-list-python-app:latest
    expose:
      - "8080"
  golang_project:
    image: flyingsmurf/go-app:latest
    expose:
      - "8080"
